# frozen_string_literal: true

source "https://rubygems.org"

# Opal - Ruby to JavaScript compiler
gem "opal", "~> 1.8"
gem "opal-sprockets", "~> 1.0"

# Required for Ruby 3.4+
gem "base64"

# Build tooling
gem "rake", "~> 13.0"

# For watching file changes during development
gem "listen", "~> 3.8"

# Testing - use minitest (native host tests are plain Ruby)
gem "minitest", "~> 5.0"

group :development do
  # Code quality
  gem "rubocop", require: false
end
